import Foundation

/// What one `push`/`pull` did, for a caller to report to the user. Counts
/// only — deliberately not the items/blobs themselves, so a future CloudKit
/// or Supabase conformance can report the same shape without also having to
/// reconstruct which specific items moved.
public struct SyncReport: Sendable, Equatable {
    /// Items appended to the destination's manifest (union-by-id — see
    /// `RemoteLibraryStore`'s doc comment).
    public var itemsCopied: Int
    /// Raw `.fit` blobs actually written to the destination. Content
    /// addressing means this can be less than `itemsCopied` — two items can
    /// share a blob that only needed writing once.
    public var blobsCopied: Int
    /// Device-alias entries that differed between the two sides and were
    /// overwritten on the destination.
    public var aliasesMerged: Int

    public init(itemsCopied: Int = 0, blobsCopied: Int = 0, aliasesMerged: Int = 0) {
        self.itemsCopied = itemsCopied
        self.blobsCopied = blobsCopied
        self.aliasesMerged = aliasesMerged
    }
}

/// Where a `LibraryStore` can be synced to/from — deliberately coarse (two
/// verbs), so a future CloudKit or Supabase implementation conforms to
/// exactly the same shape and nothing above this protocol knows which is in
/// use. The only conformance today is `FolderSyncStore`, an iCloud Drive
/// folder synced via the document picker.
///
/// **Merge policy**, binding on every conformance: raw `.fit` blobs are
/// content-addressed and therefore immutable — copy-if-absent, never
/// overwrite. Only the manifest (the item list + device-alias table) can
/// conflict: items merge by union-by-id (an item's id is assigned once, at
/// import time, and never regenerated by a sync, so the same activity always
/// unions onto the same entry rather than forking); device aliases merge
/// last-writer-wins per key, where "last write" is simply whichever side of
/// this particular `push`/`pull` call is being copied *from* — the side
/// being copied *to* gets that side's values for any key both sides know
/// about, and keeps its own values for every key the other side doesn't
/// mention.
public protocol RemoteLibraryStore: Sendable {
    /// Whether a destination has been picked and can be synced to/from yet.
    var isConfigured: Bool { get }

    /// Copies everything in `local` that the remote doesn't have yet onto
    /// the remote, and merges `local`'s device aliases onto the remote's
    /// (remote wins nothing here — `local` is the side being copied *from*).
    @discardableResult
    func push(_ local: any LibraryStore) async throws -> SyncReport

    /// Copies everything on the remote that `local` doesn't have yet into
    /// `local`, and merges the remote's device aliases onto `local`'s
    /// (`local` wins nothing here — the remote is the side being copied
    /// *from*).
    @discardableResult
    func pull(into local: any LibraryStore) async throws -> SyncReport
}
